EMOTION_CATEGORIES = {
    "admiration": "positive",
    "adoration": "positive",
    "aesthetic appreciation": "positive",
    "amusement": "positive",
    "anger": "negative",
    "anxiety": "negative",
    "awe": "positive",
    "awkwardness": "neutral",
    "boredom": "negative",
    "calmness": "neutral",
    "concentration": "neutral",
    "confusion": "neutral",
    "contemplation": "neutral",
    "contentment": "positive",
    "craving": "neutral",
    "desire": "positive",
    "determination": "positive",
    "disappointment": "negative",
    "disgust": "negative",
    "distress": "negative",
    "doubt": "negative",
    "embarrassment": "negative",
    "empathic pain": "negative",
    "entrancement": "positive",
    "envy": "negative",
    "excitement": "positive",
    "fear": "negative",
    "guilt": "negative",
    "horror": "negative",
    "interest": "positive",
    "joy": "positive",
    "love": "positive",
    "nostalgia": "neutral",
    "pain": "negative",
    "pride": "positive",
    "realization": "neutral",
    "relief": "positive",
    "romance": "positive",
    "sadness": "negative",
    "satisfaction": "positive",
    "shame": "negative",
    "surprise (negative)": "negative",
    "surprise (positive)": "positive",
    "sympathy": "positive",
    "tiredness": "neutral",
    "triumph": "positive",
}

DEFAULT_EMOTION_CATEGORY = "neutral"